#!/bin/bash
echo ls |./hsh

echo ---------

echo exit 23|./hsh
echo $?
echo ---------
echo /bin/ls |./hsh
echo ---------
echo $?
echo /bin/ls |sh
echo ---------
echo $?
echo /bin/ls |./hsh
echo $?
echo ---------
echo "/bin/ls hbk"|./hsh
echo $?
echo ---------
echo "/bin/ls hbk"|sh
echo $?
